const data = {
  inputData:{
    title:'智学格名称',
    placeholder:'做练习',
    value:'这是默认名称',
    maxLength:60
  },
  selectData:{
    title:'引导语',
    options:[
      {
        id:1,
        title:'请完成以下练习',
        checked:false
      },
      {
        id:2,
        title:'请完成以下习题',
        checked:false
      }
    ],
  },
  changeData:{
    title:'错题重做'
  }
}

export const list = [
  {
    checked:false,
    title:'《春》配乐朗读',
    teacherName:'李老师',
    school:'OK学校',
    teacherUseCount:10,
    schoolUseCount:20,
    imgUrl:''
  },
  {
    checked:false,
    title:'《春》配乐朗读',
    teacherName:'李老师',
    school:'OK学校',
    teacherUseCount:10,
    schoolUseCount:20,
    imgUrl:''
  },
  {
    checked:false,
    title:'《春》配乐朗读',
    teacherName:'李老师',
    school:'OK学校',
    teacherUseCount:10,
    schoolUseCount:20,
    imgUrl:''
  },
  {
    checked:false,
    title:'《春》配乐朗读',
    teacherName:'李老师',
    school:'OK学校',
    teacherUseCount:10,
    schoolUseCount:20,
    imgUrl:''
  },
  {
    checked:false,
    title:'《春》配乐朗读',
    teacherName:'李老师',
    school:'OK学校',
    teacherUseCount:10,
    schoolUseCount:20,
    imgUrl:''
  },
  {
    checked:false,
    title:'《春》配乐朗读',
    teacherName:'李老师',
    school:'OK学校',
    teacherUseCount:10,
    schoolUseCount:20,
    imgUrl:''
  },
  {
    checked:false,
    title:'《春》配乐朗读',
    teacherName:'李老师',
    school:'OK学校',
    teacherUseCount:10,
    schoolUseCount:20,
    imgUrl:''
  }
]

export default data
