// 添加列表
// 视频
const data = [
{
  "id": 4482803,
  "name": "简单句（一般疑问句）",
  "resType": 9,
  "region": "新东方学校",
  "duration": "7分33秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1wuJUmiDdBK.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1wuJUmiDdBK.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "王莉莉小学",
  "downloadCount": "",
  "useCount": "3",
  "viewCount": "",
  "pdfSrc": null,
  "title": "简单句（一般疑问句）",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4482802,
  "name": "简单句（特殊疑问句）",
  "resType": 9,
  "region": "新东方学校",
  "duration": "10分13秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1wuJWR6xTPi.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1wuJWR6xTPi.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "王莉莉小学",
  "downloadCount": "",
  "useCount": "3",
  "viewCount": "",
  "pdfSrc": null,
  "title": "简单句（特殊疑问句）",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4482688,
  "name": "简单句（祈使句） ",
  "resType": 9,
  "region": "新东方学校",
  "duration": "7分59秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1wuyXoreKSQ.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1wuyXoreKSQ.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "王静怡小学",
  "downloadCount": "",
  "useCount": "3",
  "viewCount": "",
  "pdfSrc": null,
  "title": "简单句（祈使句） ",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4482523,
  "name": "简单句（感叹句）",
  "resType": 9,
  "region": "新东方学校",
  "duration": "8分53秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1wuAaEMunS0.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1wuAaEMunS0.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "李想小学",
  "downloadCount": "",
  "useCount": "3",
  "viewCount": "",
  "pdfSrc": null,
  "title": "简单句（感叹句）",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4450347,
  "name": "简单句（陈述句）",
  "resType": 9,
  "region": "新东方学校",
  "duration": "8分9秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1w2JiYJouZO.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1w2JiYJouZO.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "王静怡小学",
  "downloadCount": "",
  "useCount": "3",
  "viewCount": "",
  "pdfSrc": null,
  "title": "简单句（陈述句）",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4404989,
  "name": "特殊疑问句",
  "resType": 9,
  "region": "新东方学校",
  "duration": "17分17秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1v8bHymtAkw.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1v8bHymtAkw.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "王莉莉小学",
  "downloadCount": "",
  "useCount": "4",
  "viewCount": "",
  "pdfSrc": null,
  "title": "特殊疑问句",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4404986,
  "name": "2.一般疑问句",
  "resType": 9,
  "region": "新东方学校",
  "duration": "12分31秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1v8bBPhqg8M.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1v8bBPhqg8M.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "王莉莉小学",
  "downloadCount": "",
  "useCount": "5",
  "viewCount": "",
  "pdfSrc": null,
  "title": "2.一般疑问句",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4404983,
  "name": "陈述句",
  "resType": 9,
  "region": "新东方学校",
  "duration": "10分33秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1v8bxAdOflK.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1v8bxAdOflK.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "王莉莉小学",
  "downloadCount": "",
  "useCount": "4",
  "viewCount": "",
  "pdfSrc": null,
  "title": "陈述句",
  "jsonData": null,
  "showSchoolTag": false
},
{
  "id": 4404464,
  "name": "4.选择疑问句与反义疑问句",
  "resType": 9,
  "region": "新东方学校",
  "duration": "15分10秒",
  "poster": "https://rv.okjiaoyu.cn/rv_1v7POcVMRLW.low.h264.mp4?vframe/jpg/offset/3",
  "url": "https://rv.okjiaoyu.cn/rv_1v7POcVMRLW.low.h264.mp4",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "MICROVIDEO",
  "author": "马梦恬小学",
  "downloadCount": "",
  "useCount": "4",
  "viewCount": "",
  "pdfSrc": null,
  "title": "4.选择疑问句与反义疑问句",
  "jsonData": null,
  "showSchoolTag": false
}]

// 素材
export const data2 = [
{
  "id": 5197386,
  "name": "好烦1",
  "resType": 8,
  "region": "风铃区域yace管理校",
  "duration": "",
  "poster": "",
  "url": "https://aimg.okjiaoyu.cn/aimg_-3HELaNb92vK.jpg",
  "customDirectoryId": 813621,
  "customSystemId": 10,
  "fileType": "pic",
  "author": "一校风铃教工",
  "downloadCount": "",
  "useCount": "",
  "viewCount": "",
  "pdfSrc": "",
  "title": "好烦1",
  "jsonData": null,
  "showSchoolTag": true
}]

// PPT
export const data3 = [
  {
    "id": 5197215,
    "name": " 6.14旧版不分享2校",
    "resType": 1,
    "region": "风铃区yace管理校2",
    "duration": "",
    "poster": "",
    "url": "https://rw.okjiaoyu.cn/rw_-41ofXdlYzuw.pptx",
    "customDirectoryId": 803981,
    "customSystemId": 10,
    "fileType": "ppt",
    "author": "雅思",
    "downloadCount": "",
    "useCount": "",
    "viewCount": "",
    "pdfSrc": "http://pd.okjiaoyu.cn/w_pd_-41ofXdlYzuw.pdf",
    "title": " 6.14旧版不分享2校",
    "jsonData": null,
    "showSchoolTag": false
  },
  {
    "id": 5197218,
    "name": " 6.14新版不分享2校",
    "resType": 1,
    "region": "风铃区yace管理校2",
    "duration": "",
    "poster": "",
    "url": "https://rw.okjiaoyu.cn/rw_-41maQXkFgha.pptx",
    "customDirectoryId": 803981,
    "customSystemId": 10,
    "fileType": "ppt",
    "author": "雅思",
    "downloadCount": "",
    "useCount": "",
    "viewCount": "",
    "pdfSrc": "http://pd.okjiaoyu.cn/w_pd_-41maQXkFgha.pdf",
    "title": " 6.14新版不分享2校",
    "jsonData": null,
    "showSchoolTag": false
  }
]

// 移除列表
export const dataList = [
  {
    "type": 0,
    "author": {
      "name": "风铃OKAY英语校师",
      "time": "2022-06-01",
      "region": "OKAY英语学校"
    },
    "download_count": 0,
    "file_info": {
      "file_path": "//rv.okjiaoyu.cn/rv_-6TojGaH8QsU.normal.h264.mp4",
      "type_res_file": "MICROVIDEO",
      "qiniu_code": 0,
      "pdfSrc": "",
      "poster": "https://rv.okjiaoyu.cn/rv_-6TojGaH8QsU.normal.h264.mp4?vframe/jpg/offset/3",
      "file_format": "mp4",
      "file_size": "1.3MB",
      "md5": "rv_-6TojGaH8QsU.normal.h264.mp4",
      "quality_options": [
        {
          "file_path": "//rv.okjiaoyu.cn/rv_-6TojGaH8QsU.normal.h264.mp4",
          "file_md5": "rv_-6TojGaH8QsU.normal.h264.mp4",
          "qiniu_code": 0,
          "quality_code": 1,
          "file_format": "mp4",
          "file_size": "1.3MB",
          "quality": "标清"
        }
      ]
    },
    "status": 1,
    "id": 4591148,
    "name": "新版短视频不分享1",
    "view_count": 0,
    "is_mine": false,
    "duration": "15秒",
    "is_show_tooltip": 1,
    "topic_list": [
      "Unit2 English around the world",
      "Unit2 English around the world"
    ],
    "topic_list_string": "[\"Unit2 English around the world\",\"Unit2 English around the world\"]",
    "topic_count": 2,
    "first_topic": "Unit2 English around the world",
    "use_count": 1,
    "is_fav": false,
    "is_mine_old": false,
    "difficulty": null,
    "showSchoolTag": true
  },
  {
    "type": 0,
    "author": {
      "name": "高英六四零",
      "time": "2022-06-06",
      "region": "OKAY学校"
    },
    "download_count": 0,
    "file_info": {
      "file_path": "//rv.okjiaoyu.cn/rv_-5JSM3qc5bUI.normal.h264.mp4",
      "type_res_file": "MICROVIDEO",
      "qiniu_code": 0,
      "pdfSrc": "",
      "poster": "https://rv.okjiaoyu.cn/rv_-5JSM3qc5bUI.normal.h264.mp4?vframe/jpg/offset/3",
      "file_format": "mp4",
      "file_size": "1.6MB",
      "md5": "rv_-5JSM3qc5bUI.normal.h264.mp4",
      "quality_options": [
        {
          "file_path": "//rv.okjiaoyu.cn/rv_-5JSM3qc5bUI.normal.h264.mp4",
          "file_md5": "rv_-5JSM3qc5bUI.normal.h264.mp4",
          "qiniu_code": 0,
          "quality_code": 1,
          "file_format": "mp4",
          "file_size": "1.6MB",
          "quality": "标清"
        }
      ]
    },
    "status": 1,
    "id": 5196826,
    "name": "平台视频",
    "view_count": 0,
    "is_mine": false,
    "duration": "19秒",
    "is_show_tooltip": 1,
    "topic_list": [
      "Unit1 Friendship",
      "Unit2 English around the world",
      "Unit1 Friendship",
      "Unit2 English around the world",
      "Unit1 Friendship",
      "Unit2 English around the world"
    ],
    "topic_list_string": "[\"Unit1 Friendship\",\"Unit2 English around the world\",\"Unit1 Friendship\",\"Unit2 English around the world\",\"Unit1 Friendship\",\"Unit2 English around the world\"]",
    "topic_count": 6,
    "first_topic": "Unit1 Friendship",
    "use_count": 7,
    "is_fav": false,
    "is_mine_old": false,
    "difficulty": null,
    "showSchoolTag": false
  },
  {
    "type": 0,
    "author": {
      "name": "师明婷",
      "time": "2018-09-25",
      "region": "大同第八中学"
    },
    "download_count": 0,
    "file_info": {
      "file_path": "//rv.okjiaoyu.cn/rv_12iNQl3huJq.low.h264.mp4",
      "type_res_file": "MICROVIDEO",
      "qiniu_code": 0,
      "pdfSrc": "",
      "poster": "https://rv.okjiaoyu.cn/rv_12iNQl3huJq.low.h264.mp4?vframe/jpg/offset/3",
      "file_format": "mp4",
      "file_size": "12.2MB",
      "md5": "rv_12iNQl3huJq.low.h264.mp4",
      "quality_options": [
        {
          "file_path": "//rv.okjiaoyu.cn/rv_12iNQl3huJq.low.h264.mp4",
          "file_md5": "rv_12iNQl3huJq.low.h264.mp4",
          "qiniu_code": 0,
          "quality_code": 0,
          "file_format": "mp4",
          "file_size": "12.2MB",
          "quality": "流畅"
        }
      ]
    },
    "status": 1,
    "id": 2552496,
    "name": "【微课】高中英语：阅读进阶Graded reading ---扫读的技巧",
    "view_count": 0,
    "is_mine": false,
    "duration": "7分38秒",
    "is_show_tooltip": 1,
    "topic_list": [],
    "topic_list_string": "[]",
    "topic_count": 0,
    "first_topic": "",
    "use_count": 7,
    "is_fav": false,
    "is_mine_old": false,
    "difficulty": null,
    "showSchoolTag": false
  }
]

export default data